/*
	(C) COPYRIGHT, TEXAS INSTRUMENTS INCORPORATED, 1985.  ALL
	RIGHTS RESERVED.  PROPERTY OF TEXAS INSTRUMENTS INCORPORATED.
	RESTRICTED RIGHTS - USE, DUPLICATION, OR DISCLOSURE IS SUBJECT
	TO RESTRICTIONS SET FORTH IN TI'S PROGRAM LICENSE AGREEMENT AND
	ASSOCIATED DOCUMENTATION.
*/

#ifdef	SCCSID
static char dir_h[] = "@(#)dir.h	1.4 (TI) 89/08/17";
#endif	SCCSID

#include "sys/fs/s5dir.h"
/* THIS FILE NEEDS TO BE REMOVED */
/* FROM INCLUDE STATEMENTS BEFORE */
/* THE NEXT RELEASE */
