/*
	(C) COPYRIGHT, TEXAS INSTRUMENTS INCORPORATED, 1985.  ALL
	RIGHTS RESERVED.  PROPERTY OF TEXAS INSTRUMENTS INCORPORATED.
	RESTRICTED RIGHTS - USE, DUPLICATION, OR DISCLOSURE IS SUBJECT
	TO RESTRICTIONS SET FORTH IN TI'S PROGRAM LICENSE AGREEMENT AND
	ASSOCIATED DOCUMENTATION.
*/

#ifdef	SCCSID
static char seg_h[] = "@(#)seg.h	1.3 (TI) 86/02/04";
#endif	SCCSID

/*	@(#)seg.h	2.2	UNIX System V/68 */
/*
 * Memory management addresses and bits
 */

#define	RO	SEG_PROTECT	/* access abilities */
#define	RW	0
