
/*
	(C) COPYRIGHT, TEXAS INSTRUMENTS INCORPORATED, 1986.  ALL
	RIGHTS RESERVED.  PROPERTY OF TEXAS INSTRUMENTS INCORPORATED.
	RESTRICTED RIGHTS - USE, DUPLICATION, OR DISCLOSURE IS SUBJECT
	TO RESTRICTIONS SET FORTH IN TI'S PROGRAM LICENSE AGREEMENT AND
	ASSOCIATED DOCUMENTATION.
*/

#ifdef	SCCSID
static char sysm68k_h[] = "@(#)sysm68k.h	1.11 (TI) 91/02/20";
#endif	SCCSID

#define	SYMBOL		('z'<<24)

#define SYM_PROC	0
#define SYM_SWPLO	1
#define SYM_V		2
#define SYM_CDEVSW	3
#define SYM_BDEVSW	4
#define SYM_DEVMAP	5
#define SYM_UTSNAME	6
#define SYM_SYSINFO	7
#define SYM_INODE	8
#define SYM_FILE	9
#define SYM_ISEG	10
#define SYM_SYSERR	11
#define SYM_BDEVCNT	12
#define SYM_CDEVCNT	13
#define SYM_LBOLT	14
#define SYM_TIME	15
#define SYM_MSGQUE	16
#define SYM_SEMA	17
#define SYM_SHMEM	18
#define SYM_MSGINFO	19
#define SYM_SEMINFO 	20
#define SYM_SHMINFO	21
#define SYM_CFGINFO	22
#define SYM_BPARAM	23
#define SYM_CMAP	24
#define SYM_CPULOC	25
#define SYM_END		26
#define SYM_ETEXT	27
#define SYM_FLCKINFO	28
#define SYM_STRST	29
#define SYM_MOUNT	30
#define SYM_NFSTYP	31
#define SYM_NFSDSTR	32



#define	SYMVALUE	('v'<<24)

#define SYMV_NCPU	0
#define SYMV_BDTYPE	1
