/*
	(C) COPYRIGHT, TEXAS INSTRUMENTS INCORPORATED, 1989.  ALL
	RIGHTS RESERVED.  PROPERTY OF TEXAS INSTRUMENTS INCORPORATED.
	RESTRICTED RIGHTS - USE, DUPLICATION, OR DISCLOSURE IS SUBJECT
	TO RESTRICTIONS SET FORTH IN TI'S PROGRAM LICENSE AGREEMENT AND
	ASSOCIATED DOCUMENTATION.
*/

#ifdef	SCCSID
static char s5dir_h[] = "@(#)s5dir.h	1.2 (TI) 89/08/17";
#endif	SCCSID

#ifndef	DIRSIZ
#define	DIRSIZ	14
#endif
struct	direct
{
	ushort	d_ino;
	char	d_name[DIRSIZ];
};
